name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Change this to master if your default branch is named master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: ${{ hashFiles('pnpm-lock.yaml') && 'pnpm' || hashFiles('package-lock.json') && 'npm' || '' }}

      - name: Install pnpm (If using pnpm)
        if: hashFiles('pnpm-lock.yaml') != ''
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install Dependencies
        run: |
          if [ -f pnpm-lock.yaml ]; then pnpm install --frozen-lockfile;
          elif [ -f package-lock.json ]; then npm ci;
          else npm install;
          fi

      - name: Build Static Site
        run: |
          if [ -f pnpm-lock.yaml ]; then pnpm run build;
          else npm run build;
          fi

      - name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out # Targets the generated static output directory

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4